app/Authenticator/urls.py
from django.urls import path
from django.conf.urls import include
from . import views
import Welcome.views as welcome_views


app_name = "Authenticator"

urlpatterns = [
    path('api', views.PersonViewSet.as_view({'get':'list'})),
    path('api/register-user', views.index, name="index"),
    path('Authenticator/login.html', views.login, name="login"),
    path('Welcome/index.html', welcome_views.index)
]

app/Welcome/urls.py
from django.conf.urls import include
from django.urls import path
from . import views

app_name = "Welcome"

urlpatterns = [
    path("api/apply-loan", views.apply_loan, name="apply_loan"),
    path("api/make-payment", views.make_payment, name="make_payment"),
    path("api/get-statement", views.get_statement, name="get_statement"),
    path("Welcome/transactions.html", views.transactions, name="transactions"),
    path("Welcome/index.html", views.index, name="index")
]

app/app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from rest_framework import routers
from Welcome import views as welcome_views
from Authenticator import views as authenticator_views


urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('Authenticator/', include('Authenticator.urls')),
    path('Welcome/', include('Welcome.urls')),
]

app/Welcome/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from Authenticator.models import Person

class Loan(models.Model):
  uid = models.IntegerField(unique=True)
  uuid = models.ForeignKey(Person, on_delete=models.CASCADE)
  loan_type = models.CharField(max_length=10, null=False)
  loan_amount = models.IntegerField(null=False, 
                                    validators=[MinValueValidator(150000)])
  interest_rate = models.IntegerField(null=False, 
                                      validators=[MaxValueValidator(100), 
                                                  MinValueValidator(12)])
  term_period = models.IntegerField(null=False)
  disbursement_date = models.DateField(null=False)


class Bill(models.Model):
  uid = models.IntegerField(null=False)
  loan_id = models.ForeignKey(Loan, on_delete=models.CASCADE)
  amount = models.IntegerField(null=False)
  bill_date = models.DateField(null=False)
  principal_due = models.IntegerField(default=0, null=False)
  min_due = models.IntegerField(default=0, null=False)
  term = models.IntegerField(default=1, null=False,)


class SavedState(models.Model):
  uuid = models.IntegerField(null=False)
  sid = models.IntegerField(default=1, null=False)

app/Welcome/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from urllib.parse import urlencode
from django.urls import reverse
from Authenticator.views import get_params
from Authenticator.models import Person
from .models import Loan, Bill, SavedState
from .LoanService import *


# function ```get_params_2```
def get_params_get(request, keys):
  params = {}
  for key in keys:
    params[key] = request.GET.get(key)
  return params


# function ```apply_loan```
def apply_loan(request):
  if request.method == "GET":
    try:
      params = get_params_get(request, ['uuid', 'sid', 'messages'])
      if params['sid'] is None or params['sid'] == "":
        return redirect('Authenticator:login')
      else:
        return render(request, 'Welcome/apply_loan.html', params)
    except ValueError as err:
      print("Handling illegal request", err)
      messages.info(request, "Authentication unsuccessful")
      return redirect(request, 'Authenticator:login')
  else:
    no1 = len(SavedState.objects.all())
    ss = (SavedState.objects.all()[no1 - 1])
    uuid = ss.uuid
    sid = ss.sid
    messages.info(request, "Loan request approved. Record created successfully")
    return render(request, 'Welcome/apply_loan.html', {'uuid':uuid, 'sid':sid})


# function ```index```
def index(request):
  if request.method == "GET":
    try:
      params = get_params_get(request, ['sid', 'uuid'])
      if params['sid'] is None or params['sid'] == "":
        return redirect('Authenticator:login')
      else:
        ss = SavedState.objects.create(uuid=params['uuid'], sid=params['sid'])
        ss.save()
        return render(request, "Welcome/index.html", params)
    except ValueError as err:
      print("Handling illegal request", err)
      messages.info(request, "Authentication unsuccessful")
      return redirect(request, 'Authenticator:login')
  else:
    uid = len(Loan.objects.all()) + 1
    loan_service = LoanService(uid)
    keys = ['loan_type', 'loan_amount', 'interest_rate', 'term_period', 'disbursement_date']
    saved_states = SavedState.objects.all()
    no1 = len(saved_states)
    ss = saved_states[no1 - 1]
    uuid = ss.uuid
    sid = ss.sid
    params = get_params(request, keys)
    usr = Person.objects.get(uuid=uuid)
    if usr is not None:
      if loan_service.validate_request(params, usr.annual_income, 30):
        loan = Loan.objects.create(uid=uid, uuid=usr, loan_type=params['loan_type'],
                        loan_amount=params['loan_amount'], 
                        interest_rate=params['interest_rate'], 
                        term_period=params['term_period'], 
                        disbursement_date=params['disbursement_date'])
        loan.save()
        #
        messages.info(request, "Loan entry created successfully")
        base_url = reverse('Welcome:apply_loan')
        query_string = urlencode({'sid':sid, 'uuid':uuid, 'messages':messages})
        url = '{}?{}'.format(base_url, query_string)
        return redirect(request, url)
    else:
      messages.info(request, "Authentication unsuccessful")
      return redirect(request, 'Authenticator:login')


def make_payment(request):
  if request.method == "GET":
    params = get_params_get(request, ['sid', 'uuid'])
    return render(request, 'Welcome/make_payment.html', params)
  else:
    params = get_params(request, ['loan_id', 'amount'])
    loan_id = params['loan_id']
    amount = params['amount']
    ls1 = Payment(loan_id)
    try:
      ls1.make_payment(amount)
      messages.info(request, "Payment made successfully")
      return render(request, 'Welcome/make_payment.html', params)
    except ValueError as err:
      print("ValueError", err)
      return redirect('Authenticator:login')


def get_statement(request):
  if request.method == "GET":
    params = get_params_get(request, ['sid', 'uuid', 'loan_id'])
    loan_id = params['loan_id']
    if loan_id is not None or loan_id != "":
      ls1 = Payment(loan_id)
      context = {}
      context['sid'] = params['sid']
      context['uuid'] = params['uuid']
      context['loan_id'] = loan_id
      context['due_payments'] = ls1.getDueDates()
      context['past_transactions'] = ls1.getPastTransactions()
      base_url = reverse('Welcome:transactions')
      query_string = urlencode(context)
      url = '{}?{}'.format(base_url, query_string)
      return redirect(url)
    else:
      return render(request, 'Welcome/get_statement.html', params)

  
def transactions(request):
  if request.method == "GET":
    params = get_params_get(request, ['sid', 'uuid', 'loan_id', 'due_payments', 
                                    'past_transactions'])
    return render(request, 'Welcome/transactions.html', params)

app/Welcome/templates/Welcome/apply_loan.html
<!DOCTYPE html>
<head>
    <title>
        Credit Service
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>
<body>
    <section>
        <h1>
            Credit Service
        </h1>
        {% if messages %}
        <div class="alert alert-success" role="alert">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </div>
        {% endif %}
        <button class="btn"><a href="{% url 'Welcome:index' %}?sid={{sid}}&uuid={{uuid}}">Back</a></button>
    </section>
    <footer style="text-align: center;">
        Siddharth Bhatore
    </footer>
</body>

app/Welcome/templates/Welcome/get_statement.html
<!DOCTYPE html>
<head>
    <title>
        CreditService
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>
<body>
    <section>
        <div style="float:right">
            <span>{{ sid }}</span>
            <span>{{ uuid }}</span>
            <button class="btn"><a href="{% url 'Welcome:index' %}?sid={{sid}}&uuid={{uuid}}">Back</a></button>
            <button class="btn"><a href="{% url 'Authenticator:login' %}">Logout</a></button>
        </div>
        <h1>
            Credit Service
        </h1>
        <form method="get" action="{% url 'Welcome:get_statement' %}">
            <label for="loan_id">Loan ID</label>
            <input type="number" name="loan_id">
            <input type="submit" value="Submit" class="btn btn-primary">
        </form>
    </section>
    <footer style="text-align: center;">
        Siddharth Bhatore
    </footer>
</body>

app/Welcome/templates/Welcome/index.html
<!DOCTYPE html>
<head>
    <title>CreditService</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>
<body>
    <section>
        <div id="logout" style="float: right; margin-right: 10%;">
            <span>{{ sid }}</span>
            <span>{{ uid }}</span>
            <button class="btn">
                <a href="{% url 'Authenticator:login'%}">Logout</a>
            </button>
        </div>
        <h1>Welcome: CreditService</h1>
        <button class="btn">
            <a href="{% url 'Welcome:make_payment' %}?sid={{sid}}&uuid={{uuid}}">Make Payment</a>
        </button>
        <button class="btn">
            <a href="{% url 'Welcome:transactions' %}?sid={{sid}}&uuid={{uuid}}">Transactions</a>
        </button>
        <br>
        <h2>Loan Details</h2>
        {% if messages %}
        <div class="alert alert-danger" role="alert">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </div>
        {% endif %}
        <div id="loan_details">
            <form method="post" action="{% url 'Welcome:apply_loan' %}" class="form">
                {% csrf_token %}
                <div class="mb-3 mt-3">
                    <label for="loan_type" class="form-label">Loan Type</label>
                    <input type="radio" name="loan_type" value="CREDIT">
                    <label for="loan_type" class="form-label">CREDIT</label>
                    <input type="radio" name="loan_type" value="DEBIT">
                    <label for="loan_type" class="form-label">DEBIT</label>
                    <br>
                    <label for="loan_amount" class="form-label">Loan Amount</label>
                    <input type="number" name="loan_amount" class="form-control">
                    <br>
                    <label for="interest_rate" class="form-label">Interest Rate</label>
                    <input type="number" name="interest_rate" class="form-control">
                    <br>
                    <label for="term_period" class="form-label">Term Period</label>
                    <input type="number" name="term_period" class="form-control">
                    <br>
                    <label for="disbursement_date" class="form-label">Disbursement Date</label>
                    <input type="date" name="disbursement_date" class="form-control">
                    <br>
                </div>
                <input type="submit" value="Submit" class="btn btn-primary" class="form-control">
            </form>
        </div>
    </section>
    <footer style="text-align: center;">
        Siddharth Bhatore
    </footer>
</body>

app/Welcome/templates/Welcome/make_payment.html
<!DOCTYPE html>
<head>
    <title>
        CreditService
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>
<body>
    <section>
        <div style="float:right">
            <span>{{ sid }}</span>
            <span>{{ uuid }}</span>
            <button class="btn"><a href="{% url 'Welcome:index' %}?sid={{sid}}&uuid={{uuid}}">Back</a></button>
            <button class="btn"><a href="{% url 'Authenticator:login' %}">Logout</a></button>
        </div>
        <h1>
            Credit Service
        </h1>
        <div id = "make_payment">
            <form action="{% url 'Welcome:make_payment' %}" method="post">
                {% csrf_token %}
                <div class="mb-3 mt-3">
                    <label for="loan_id">Loan Id</label>
                    <input type="number" name="loan_id">
                    <label for="amount">Amount</label>
                    <input type="number" name="amount">
                    <input type="submit" value="submit" class="btn btn-primary">
                </div>
            </form>
        </div>
    </section>
    <footer style="text-align: center;">
        Siddharth Bhatore
    </footer>
</body>

app/Welcome/templates/Welcome/transactions.html
<!DOCTYPE html>
<head>
    <title>
        CreditService
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>
<body>
    <section>
        <div id="logout" style="float: right; margin-right: 10%;">
            <span>{{ sid }}</span>
            <span>{{ uid }}</span>
            <button class="btn">
                <a href="{% url 'Welcome:index' %}?sid={{sid}}&uuid={{uuid}}">
                    Back
                </a>
            </button>
            <button class="btn">
                <a href="{% url 'Authenticator:login'%}">Logout</a>
            </button>
        </div>

        <h1>
            Credit Service
        </h1>
        <div id="past_transactions">
        {% if loan_id %}   
            <table>
                <thead>
                    Past Transactions
                </thead>
                {% for transaction in past_transactions %}
                <tr>
                    {% for member in transaction %}
                    <td>
                        {{ member }}
                    </td>
                    {% endfor %}
                </tr>
                {% endfor %}
            </table>
        {% endif %}
        </div>
        <div id="upcoming_transactions">
            {% if loan_id %}   
                <table>
                    <thead>
                        Upcoming Transactions
                    </thead>
                    {% for payment in due_payments %}
                    <tr>
                        {% for member in payment %}
                        <td>
                            {{ member }}
                        </td>
                        {% endfor %}
                    </tr>
                    {% endfor %}
                </table>
            {% endif %}
            </div>
    </section>
    <footer style="text-align: center;">Siddharth Bhatore</footer>
</body>