app/Authenticator/urls.py
from django.urls import path
from django.conf.urls import include
from . import views
import Welcome.views as welcome_views


app_name = "Authenticator"

urlpatterns = [
    path('api', views.PersonViewSet.as_view({'get':'list'})),
    path('api/register-user', views.index, name="index"),
    path('Authenticator/login.html', views.login, name="login"),
    path('Welcome/index.html', welcome_views.index)
]

app/app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from rest_framework import routers
from Welcome import views as welcome_views
from Authenticator import views as authenticator_views


urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('Authenticator/', include('Authenticator.urls')),
    path('Welcome/', include('Welcome.urls')),
]

app/Authenticator/models.py
from django.db import models


class Person(models.Model):
  uuid = models.IntegerField(auto_created=True, unique=True)
  name = models.CharField(max_length=20)
  email = models.CharField(max_length=30, unique=True)
  annual_income = models.IntegerField()
  password = models.CharField(max_length=8)


class Session(models.Model):
  uuid = models.ForeignKey(Person, on_delete=models.CASCADE)
  sid = models.IntegerField()

app/Authenticator/views.py
from django.shortcuts import render, redirect
from urllib.parse import urlencode
from django.urls import reverse
from .models import Person, Session
from django.contrib import messages
from rest_framework import viewsets, permissions
from .serializers import PersonSerializer

class Authenticator():
  
  def __init__(self, usr):
    self.usr = usr
  
  def authenticate(self, password): 
    if self.usr.uuid is not None:
      session = Session.objects.get(uuid=self.usr)
      if (password == self.usr.password):
        if session is None or session.sid == "":
          return ""
        else:
          return session.sid
      else:
        return ""
    else:
      return ""


class PersonViewSet(viewsets.ModelViewSet):
    
    queryset = Person.objects.all().order_by('uuid')
    serializer_class = PersonSerializer
    permission_classes = [permissions.IsAuthenticated]


def get_params(request, keys):
  params = {}
  for key in keys:
    params[key] = request.POST[key]
  return params


def index(request):
  if request.method == "GET":
    return render(request, 'Authenticator/index.html')
  else:
    params = get_params(request, ['name', 'email', 'annual_income', 'password'])
    uuid = len(Person.objects.all()) + 1
    usr = Person.objects.create(uuid=uuid, name=params["name"], email=params["email"], 
                                annual_income=params["annual_income"], 
                                password=params["password"])
    usr.save()
    sid = len(Session.objects.all()) + 1
    session = Session.objects.create(uuid=usr, sid=sid)
    session.save()
    return redirect("Authenticator:login")



def login(request):
  if request.method == "GET":
    return render(request, "Authenticator/login.html")
  else:
    params = get_params(request, ['email', 'password'])
    usr = Person.objects.get(email=params["email"])  
    auth = Authenticator(usr)
    session_id = auth.authenticate(params["password"])
    if session_id != "" and session_id is not None:
      base_url = reverse('Welcome:index')
      query_string = urlencode({'sid':session_id, 'uuid':usr.uuid})
      url = '{}?{}'.format(base_url, query_string)
      return redirect(url)
    else:
      messages.info(request, 'Password incorrect')
      return render(request, "Authenticator/login.html")

app/Authenticator/templates/Authenticator/index.html
<!DOCTYPE html>
<head>
    <title>Credit Service</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>
<body>
    <section>
        <div>
            <button class="btn">
                <a href="{% url 'Authenticator:login' %}">Login</a>
            </button>
        </div>
        <h1>
            Credit Service
        </h1>
        {% if messages %}
        <div class="alert alert-danger" role="alert">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </div>
        {% endif %}
        <form method="post" action="{% url 'Authenticator:index' %}" class="form">
            {% csrf_token %}
            <div class="mb-3 mt-3">
                <label for="name" class="form-label">Name</label>
                <input type="text" name="name" class="form-control">
                <label for="email" class="form-label">Email</label>
                <input type="text" name="email" class="form-control">
                <label for="annual_income" class="form-label">Income</label>
                <input type="text" name="annual_income" class="form-control">
                <label for="password" class="form-label">Password</label>
                <input type="password" name="password" class="form-control">
                <input type="submit" value="Submit" class="btn btn-primary">
            </div>
        </form>
    </section>
</body>

app/Authenticator/templates/Authenticator/login.html
<!DOCTYPE html>
<head>
    <title>Credit Service</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>
<body>
    <section>
        <button class="btn">
            <a href="{% url 'Authenticator:index' %}">Login</a>
        </button>
        <h1>
            Credit Service
        </h1>
        {% if messages %}
        <div class="alert alert-danger" role="alert">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </div>
        {% endif %}
        <form method="post" action="{% url 'Authenticator:login' %}" class="form">
            {% csrf_token %}
            <label for="email" class="form-label">Email</label>
            <input name="email" class="form-control">
            <label for="password" class="form-label">Password</label>
            <input type="password" name="password" class="form-control">
            <input type="submit" value="Submit" class="btn btn-primary">
        </form>
    </section>
</body>